Add a CI job that checks that the example in `README.md` matches the `example.yml` file
JuliaRegistries/TagBot pull request #210
Opened 2021-08-15 06:52 UTC by DilumAluthge

Currently, the example TagBot workflow is defined in two different sources in this repository:
1. The `example.yml` file
2. The `Setup` section of the `README.md`

Therefore, there is a risk that a change is made to one of the two sources but is not made to the other sources, resulting in the two sources getting out of sync.

This PR adds a simple CI check to make sure that the example in `README.md` matches the `example.yml` file.

2021-08-29 04:17 UTC, DilumAluthge commented
Bump @christopher-dG

2021-08-31 04:15 UTC, christopher-dG requested changes
Personally I feel like shell is enough for this, but I do agree with the premise of this PR

2021-08-31 04:15 UTC, christopher-dG commented on .github/workflows/check_readme.yml
> +      - master
```suggestion
```
I'd rather just do all PRs

2021-08-31 04:15 UTC, christopher-dG commented on .github/workflows/check_readme.yml
> +      - '*'
```suggestion
```

No need for CI on tags, they're automated

2021-08-31 04:15 UTC, christopher-dG commented on .github/workflows/check_readme.yml
> +      - run: julia --color=yes --project=.ci -e 'include(".ci/check_readme.jl"); check_readme(pwd())'
I feel like we can just keep this minimal with Bash
```suggestion
      - run: |
          readme="$(<README.md)"
          example="$(echo -e "\`\`\`yml\n$(<example.yml)\n\`\`\`")"
          [[ "$readme" == *"$example"* ]]
```

2021-08-31 04:15 UTC, christopher-dG commented on .github/workflows/check_readme.yml
> +name: Check README
```suggestion
name: Compare example workflows
```

2021-08-31 05:06 UTC, merged